import React from 'react';

const html = "<div class=\"admin-shell\">\r\n    <aside class=\"admin-sidebar\">\r\n      <div class=\"admin-brand\">\r\n        <img src=\"/assets/ifoodentregadores.webp\" alt=\"iFood\" />\r\n        <div>\r\n          <strong>Dashboard</strong>\r\n          <span>Entregadores</span>\r\n        </div>\r\n      </div>\r\n      <nav class=\"admin-nav\">\r\n        <a class=\"admin-nav-item\" data-admin=\"overview\" href=\"/admin\">Visao geral</a>\r\n        <a class=\"admin-nav-item\" data-admin=\"tracking\" href=\"/admin/tracking\">Tracking</a>\r\n        <a class=\"admin-nav-item\" data-admin=\"utmfy\" href=\"/admin/utmfy\">UTMfy</a>\r\n        <a class=\"admin-nav-item\" data-admin=\"pages\" href=\"/admin/pages\">Paginas</a>\r\n        <a class=\"admin-nav-item\" data-admin=\"leads\" href=\"/admin/leads\">Leads</a>\r\n      </nav>\r\n      <div class=\"admin-sidebar-foot\">\r\n        <span class=\"admin-pill\">Seguro</span>\r\n        <span class=\"admin-muted\">Painel privado</span>\r\n      </div>\r\n    </aside>\r\n\r\n    <main class=\"admin-main\">\r\n      <header class=\"admin-topbar\">\r\n        <div>\r\n          <h1>Paginas</h1>\r\n          <p>Veja o volume por pagina e identifique onde o lead interrompe o fluxo.</p>\r\n        </div>\r\n      </header>\r\n\r\n      <section id=\"admin-login\" class=\"admin-login-card\">\r\n        <h2>Acesso restrito</h2>\r\n        <p class=\"admin-muted\">Digite sua senha para acessar o painel.</p>\r\n        <div class=\"input-group\">\r\n          <input type=\"password\" id=\"admin-password\" class=\"floating-input\" placeholder=\" \" autocomplete=\"current-password\" />\r\n          <label for=\"admin-password\" class=\"floating-label\">Senha do admin</label>\r\n        </div>\r\n        <button id=\"admin-login-btn\" class=\"btn-primary\" type=\"button\">Entrar</button>\r\n        <div id=\"admin-login-error\" class=\"form-error hidden\"></div>\r\n      </section>\r\n\r\n      <div id=\"admin-panel\" class=\"admin-panel hidden\">\r\n        <section class=\"admin-section admin-section--card\">\r\n          <div class=\"admin-section-header\">\r\n            <h2>Insights do funil</h2>\r\n            <span class=\"admin-chip\">Diagnostico</span>\r\n          </div>\r\n          <p class=\"admin-hint\">Compare cada etapa e veja onde esta a maior queda.</p>\r\n          <div class=\"admin-insights-grid\" id=\"pages-insights\"></div>\r\n        </section>\r\n\r\n        <section id=\"admin-pages\" class=\"admin-section\">\r\n          <div class=\"admin-section-header\">\r\n            <h2>Paginas e fluxo</h2>\r\n            <span class=\"admin-chip\">Pageviews</span>\r\n          </div>\r\n          <div class=\"admin-pages-grid\" id=\"pages-grid\"></div>\r\n        </section>\r\n      </div>\r\n    </main>\r\n  </div>\r\n\r\n  <div id=\"toast\" class=\"toast hidden\" role=\"status\" aria-live=\"polite\"></div>";

export default function AdminPagesPage() {
  return <div className="page-root" dangerouslySetInnerHTML={{ __html: html }} />;
}



